Configeditor settings tab
souslesens/souslesensVocables pull request #782
Opened 2024-06-20 19:55 UTC by fbessou

Closes #762 
![image](https://github.com/souslesens/souslesensVocables/assets/6593665/aca52d2b-b357-41af-bf1e-16f3b547334b)

2024-06-21 09:15 UTC, fbessou commented
Ajouter feedback après sauvegarde.
Checkbox dans les selecteurs.
Retirer les dividers.
"Save Settings" centré

2024-06-28 09:26 UTC, xgaia requested changes

2024-06-28 09:26 UTC, xgaia commented on model/tools.js
> +    // This list must be synced with /public/vocables/config/tools.js
il faudrait lire cette directement le fichier tools.js

2024-07-04 08:31 UTC, xgaia approved these changes

2024-07-04 13:20 UTC, merged